name: 'Paragraph Pull Runner'
description: 'Pulls updated code from paragon and sync with github branch'
inputs:
  projectId:
    type: string
    required: true
  commitId:
    type: string
    required: true
  paragonKey:
    type: string
    required: true
  npmToken:
    type: string
    required: true
  paragonZeusUrl:
    type: string
    required: true
  paragonDashboardUrl:
    type: string
    required: true
  subfolder:
    type: string
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Validate Inputs
      id: validate
      shell: bash
      run: |
        if [ -z "${{ inputs.projectId }}" ]; then
          echo "projectId is not provided."
          exit 1
        fi
          
        if [ -z "${{ inputs.commitId }}" ]; then
          echo "commitId is not provided."
          exit 1
        fi 

        if [ -z "${{ inputs.paragonKey }}" ]; then
          echo "paragonKey is not provided."
          exit 1
        fi 

        if [ -z "${{ inputs.npmToken }}" ]; then
          echo "npmToken is not provided."
          exit 1
        fi 

        if [ -z "${{ inputs.paragonZeusUrl }}" ]; then
          echo "paragonZeusUrl is not provided."
          exit 1
        fi 

        if [ -z "${{ inputs.paragonDashboardUrl }}" ]; then
          echo "paragonDashboardUrl is not provided."
          exit 1
        fi

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.1
      with:
        node-version: v18.17.1

    - name: Install para CLI
      shell: bash
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npmToken }}" > ~/.npmrc
        npm install -g @useparagon/cli@0.0.1-canary.36

    - name: Authenticate into CLI
      env:
        PARAGON_CLI_KEY: ${{ inputs.paragonKey }}
        PARAGON_HOST_DASHBOARD: ${{ inputs.paragonDashboardUrl }}
        PARAGON_HOST_ZEUS: ${{ inputs.paragonZeusUrl }}
      shell: bash
      run: |
        mkdir -p ~/.paragon
        cat << EOF > ~/.paragon/credentials.json
        {
          "default": {
            "profile": "default",
            "token": "$PARAGON_CLI_KEY"
          }
        }
        EOF
        cat << EOF > ~/.paragon/profiles.json
        {
          "default": {
            "name": "default",
            "default": true,
            "services": {
              "zeus": "$PARAGON_HOST_ZEUS",
              "dashboard": "$PARAGON_HOST_DASHBOARD"
            }
          }
        }
        EOF

    - name: Pull changes
      shell: bash
      run: |
        cd ${{ inputs.subfolder }}
        para pull

    - name: Commit changes
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ⤵️ Sync changes from remote

    # Post steps
    - name: Update success status in Paragon
      shell: bash
      env:
        PARAGON_CLI_KEY: ${{ inputs.paragonKey }}
        PARAGON_HOST_ZEUS: ${{ inputs.paragonZeusUrl }}
        PROJECT_ID: ${{ inputs.projectId }}
        COMMIT_ID: ${{ inputs.commitId }}
      if: ${{ success() }}
      run: |
        echo "Commit succeeded!"
        curl -X PATCH \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $PARAGON_CLI_KEY" \
          -d "{ \"projectId\": \"$PROJECT_ID\", \"commitId\": \"$COMMIT_ID\", \"runId\": \"${{ github.run_id }}\", \"success\": true, \"hash\": \"${{ steps.commit.outputs.commit_hash }}\"  }" \
          $PARAGON_HOST_ZEUS/graphite/projects/commit

    - name: Update failed status in Paragon
      shell: bash
      env:
        PARAGON_CLI_KEY: ${{ inputs.paragonKey }}
        PARAGON_HOST_ZEUS: ${{ inputs.paragonZeusUrl }}
        PROJECT_ID: ${{ inputs.projectId }}
        COMMIT_ID: ${{ inputs.commitId }}
      if: ${{ failure() }}
      run: |
        echo "Commit failed!"
        curl -X PATCH \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $PARAGON_CLI_KEY" \
          -d "{ \"projectId\": \"$PROJECT_ID\", \"commitId\": \"$COMMIT_ID\", \"runId\": \"${{ github.run_id }}\", \"success\": false }" \
          $PARAGON_HOST_ZEUS/graphite/projects/commit
